TunnelAppSubscription/Models/Users/Roles/RolesSelectionDTO.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TunnelApp.Subscription.Models.Users.Roles
{
    public class RolesSelectionDTO
    {
        public string SelectedRole { get; set; }
        public bool Checked { get; set; }
        public Guid IdSelectedRole { get; set; }
    }
}

TunnelAppSubscription/Models/Users/UsersFormModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using TunnelApp.Subscription.Models.Users.Roles;

namespace TunnelApp.Subscription.Models.Users
{
    public class UsersFormModel
    {
        public Guid IdUser { get; set; }

        [Display(Name = "User Name")]
        public string DbUserName { get; set; }

        [Display(Name = "First Name")]
        public string FirstName { get; set; }

        [Display(Name = "Last Name")]
        public string LastName { get; set; }

        [Display(Name = "Contact")]
        public string Contact { get; set; }

        [Display(Name = "Password")]
        public string Password { get; set; }

        [Display(Name = "Old Password")]
        public string OldPassword { get; set; }

        [Display(Name = "Email")]
        public string Email { get; set; }

        [Display(Name = "User Roles")]
        public List<RolesSelectionDTO> SelectedRoles { get; set; }

        [Display(Name = "Change Password?")]
        public bool PasswordChange { get; set; }

        [Display(Name = "Client")]
        public Guid IdClient { get; set; }

        public string UserName { get; set; }
    }
}

TunnelAppSubscription/Controllers/ManagerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TunnelApp.Subscription.Controllers
{
    public class ManagerController : Controller
    {
        //
        // GET: /Manager/

        public ActionResult Index()
        {
            return View();
        }

        //
        // GET: /Manager/Clients

        public ActionResult Clients()
        {
            return RedirectToAction("Index", "Clients");
        }

        //
        // GET: /Manager/Subscriptions

        public ActionResult Subscriptions()
        {
            return RedirectToAction("Index", "Subscriptions");
        }

        //
        // GET: /Manager/AppModules

        public ActionResult AppModules()
        {
            return RedirectToAction("Index", "AppModules");
        }

        //
        // GET: /Manager/Projects

        public ActionResult Projects()
        {
            return RedirectToAction("Index", "Projects");
        }

        //
        // GET: /Manager/Tunnels

        public ActionResult Tunnels()
        {
            return RedirectToAction("Index", "Tunnels");
        }

        //
        // GET: /Manager/Faces

        public ActionResult Faces()
        {
            return RedirectToAction("Index", "Faces");
        }

        //
        // GET: /Manager/Users

        public ActionResult Users()
        {
            return RedirectToAction("Index", "Users");
        }

        //
        // GET: /Manager/ModelTraining

        public ActionResult ModelTraining()
        {
            return RedirectToAction("Index", "ModelTraining");
        }
    }
}

TunnelAppSubscription/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TunnelApp.Subscription.Models.Users;

namespace TunnelApp.Subscription.Controllers
{
    public class UsersController : Controller
    {
        //
        // GET: /Users/

        public ActionResult Index()
        {
            UsersViewModel model = new UsersViewModel();
            return View(model);
        }

        //
        // GET: /Users/Create
        [HttpGet]
        public ActionResult Create()
        {
            UsersViewModel model = new UsersViewModel(User.Identity.Name);
            return View(model);
        }

        //
        // POST: /Users/Create
        [HttpPost]
        public ActionResult Create(UsersFormModel form)
        {
            UsersViewModel model = new UsersViewModel(form);

            try
            {
                if (ModelState.IsValid)
                {
                    form.UserName = User.Identity.Name;

                    string errorMessage = model.createMembership();

                    if (!string.IsNullOrEmpty(errorMessage))
                    {
                        Mensaje = errorMessage;
                        model.FORM = form;
                        return View(model);
                    }

                    model.create();
                    Mensaje = "Client User created successfully.";
                    return RedirectToAction("Index");
                }
            }
            catch (Exception e)
            {
                Mensaje = "Changes couldn't be saved. Please, try again later. If the problem persist, please contact to Support Help Desk.";
            }
            return View(model);
        }

        //
        // GET: /Users/Edit
        [HttpGet]
        public ActionResult Edit(Guid IdUser)
        {
            UsersViewModel model = new UsersViewModel(IdUser);
            return View(model);
        }

        //
        // POST: /Users/Edit
        [HttpPost]
        public ActionResult Edit(UsersFormModel form)
        {
            UsersViewModel model = new UsersViewModel(form);

            try
            {
                if (ModelState.IsValid)
                {
                    form.UserName = User.Identity.Name;
                    model.update();
                    Mensaje = "Changes saved successfully.";

                    if (User.Identity.Name.ToLower() != form.DbUserName.ToLower())
                    {
                        return RedirectToAction("Index");
                    }
                }
            }
            catch (Exception e)
            {
                model = new UsersViewModel(form.IdUser);
                Mensaje = "Changes couldn't be saved. Please, try again later. If the problem persist, please contact to Support Help Desk.";
            }
            return View(model);
        }


        //
        // GET: /Users/EditUser
        [HttpGet]
        public ActionResult EditUser(Guid IdUser)
        {
            UsersViewModel model = new UsersViewModel(IdUser);
            return View(model);
        }

        //
        // POST: /Users/EditUser
        [HttpPost]
        public ActionResult EditUser(UsersFormModel form)
        {
            UsersViewModel model = new UsersViewModel(form);

            try
            {
                if (ModelState.IsValid)
                {
                    form.UserName = User.Identity.Name;

                    string errorMessage = model.updateMembership();

                    if (!string.IsNullOrEmpty(errorMessage))
                    {
                        Mensaje = errorMessage;
                        model.FORM = form;
                        return View(model);
                    }

                    model.updateUser();

                    if (User.Identity.Name.ToLower() == form.DbUserName.ToLower())
                    {
                        Mensaje = "Changes saved successfully. You have to sign in again for changes take effect.";
                        return RedirectToAction("LogOff", "Account");
                    }

                    Mensaje = "Changes saved successfully.";
                    return RedirectToAction("Index");
                }
            }
            catch (Exception e)
            {
                model = new UsersViewModel(form.IdUser);
                Mensaje = "Changes couldn't be saved. Please, try again later. If the problem persist, please contact to Support Help Desk.";
            }
            return View(model);
        }

        //
        // GET: /Users/Delete
        [HttpGet]
        public ActionResult Delete(Guid IdUser)
        {
            UsersViewModel model = new UsersViewModel(IdUser);
            model.delete();
            Mensaje = "Subscription deleted successfully.";
            return RedirectToAction("Index");
        }

        //
        // GET: /Users/ResetPassword
        [HttpGet]
        public ActionResult ResetPassword(Guid IdUser)
        {
            UsersViewModel model = new UsersViewModel(IdUser);
            model.resetPassword();
            Mensaje = "Password reset successfully. For more information, check the icon on Reset Password column.";
            return RedirectToAction("Index");
        }

        public string Mensaje
        {
            set
            {
                TempData["Mensaje"] = value;
            }
        }
    }
}

TunnelAppSubscription/Views/Users/Create.cshtml
@model TunnelApp.Subscription.Models.Users.UsersViewModel
@using System.Web.Optimization
@{
    ViewBag.Title = "Create New User";
}
<div class="row-fluid">
				<ol class="breadcrumb">
					<li><a href="@Url.Action("Index", "Home")">Home</a></li>
					<li><a href="@Url.Action("Index", "Manager")">Manager</a></li>
					<li><a href="@Url.Action("Index", "Users")">Users</a></li>
					<li><a href="@Url.Action("Create", "Users")">New</a></li>
				</ol>
			</div>

			<section>
				<div class="row-fluid">
					<h3>Create New User</h3>
				</div>
                @if (TempData["Mensaje"] != null && !String.IsNullOrEmpty(TempData["Mensaje"].ToString()))
                {
                <div class="alert alert-warning alert-dismissible fadeOutMantenedor" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <strong>@(TempData["Mensaje"])</strong>
                </div>
                }
                <br />
                <form action="@Url.Action("Create", "Users")" method="POST" class="form-horizontal">
				<div class="row-fluid">
                        <div class="form-group">
					        <label class="col-sm-4 control-label">@Html.LabelFor(x => x.FORM.IdClient)</label>
						    <div class="col-sm-6">
                                @Html.DropDownListFor(x => x.FORM.IdClient, Model.clients, "Choose Client", new { @class = "form-control input-sm" })
						    </div>
					    </div>
						<div class="form-group">
							<label class="col-sm-4 control-label">@Html.LabelFor(x => x.FORM.FirstName)</label>
							<div class="col-sm-6">
                                @Html.TextBoxFor(x => x.FORM.FirstName, new { @class = "form-control input-sm", @placeholder = "First Name" })
							</div>
						</div>
						<div class="form-group">
							<label class="col-sm-4 control-label">@Html.LabelFor(x => x.FORM.LastName)</label>
							<div class="col-sm-6">
                                @Html.TextBoxFor(x => x.FORM.LastName, new { @class = "form-control input-sm", @placeholder = "Last Name" })
							</div>
						</div>
						
                    <div class="form-group">
							<label class="col-sm-4 control-label">@Html.LabelFor(x => x.FORM.Contact)</label>
							<div class="col-sm-6">
                                @Html.TextBoxFor(x => x.FORM.Contact, new { @class = "form-control input-sm", @placeholder = "Ej: 22225555 (Opcional)" })
							</div>
						</div>
                    <div class="form-group">
							<label class="col-sm-4 control-label">@Html.LabelFor(x => x.FORM.Email)</label>
							<div class="col-sm-6">
                                @Html.TextBoxFor(x => x.FORM.Email, new { @class = "form-control input-sm", @placeholder = "Ej: jsmith@gmail.com" })
							</div>
						</div>
                    <hr />
                    <div class="form-group">
							<label class="col-sm-4 control-label">@Html.LabelFor(x => x.FORM.DbUserName)</label>
							<div class="col-sm-6">
                                @Html.TextBoxFor(x => x.FORM.DbUserName, new { @class = "form-control input-sm", @placeholder = "jsmith" })
							</div>
						</div>
                    <div class="form-group">
							<label class="col-sm-4 control-label">@Html.LabelFor(x => x.FORM.Password)</label>
							<div class="col-sm-6">
                                @Html.TextBoxFor(x => x.FORM.Password, new { @class = "form-control input-sm", @type = "password" })
							</div>
						</div>
                    <div class="form-group">
							<label class="col-sm-4 control-label">Repita Contraseña</label>
							<div class="col-sm-6">
                                <input type="password" class="form-control input-sm" />
							</div>
						</div>
                    <div class="form-group">
						    <label class="col-sm-4 control-label">@Html.LabelFor(x => x.FORM.SelectedRoles)</label>
							<div class="col-sm-6">
                                @for (int i = 0; i < Model.FORM.SelectedRoles.Count(); i++)
                                {
                                   <div class="checkbox"><label>@Html.CheckBoxFor(m => m.FORM.SelectedRoles[i].Checked, new { @id = Model.FORM.SelectedRoles[i].IdSelectedRole}) @Model.FORM.SelectedRoles[i].SelectedRole </label></div>
                                   @Html.HiddenFor(m => m.FORM.SelectedRoles[i].IdSelectedRole)
                                   @Html.HiddenFor(m => m.FORM.SelectedRoles[i].SelectedRole)
                                }
							</div>
						</div>	
                    <br />						
				</div>
				<div class="row">
					<div class="col-md-6 col-md-offset-4">
						<input type="submit" class="btn btn-success pull-right" value="Save" />
                        <a href="@Url.Action("Index", "Users")" class="btn btn-primary">Cancel</a>
					</div>
                    
				</div>
                </form>
			</section>
@Scripts.Render("~/bundles/custom/manager/users/create")
<script type="text/javascript">
    $(document).ready(function () {
        init();
    });
</script>

TunnelAppSubscription/Views/Users/Edit.cshtml
@model TunnelApp.Subscription.Models.Users.UsersViewModel
@using System.Web.Optimization
@{
    ViewBag.Title = "Edit User - Private Data";
}

<div class="row-fluid">
				<ol class="breadcrumb">
					<li><a href="@Url.Action("Index", "Home")">Inicio</a></li>
					<li><a href="@Url.Action("Index", "Manager")">Manager</a></li>
					<li><a href="@Url.Action("Index", "Users")">Users</a></li>
					<li>Edit</li>
				</ol>
			</div>
			<section>
                
				<div class="row-fluid">
					<h3>Edit Private Data</h3>
				</div>
                @if (TempData["Mensaje"] != null && !String.IsNullOrEmpty(TempData["Mensaje"].ToString()))
                {
                <div class="alert alert-warning alert-dismissible fadeOutMantenedor" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <strong>@(TempData["Mensaje"])</strong>
                </div>
                }
                <br />
                <form action="@Url.Action("Edit", "Users")" method="POST" class="form-horizontal">
                    @Html.HiddenFor(x => x.FORM.IdUser)
                    @Html.HiddenFor(m => m.FORM.DbUserName, @Model.FORM.DbUserName)
				<div class="row-fluid">
                    <div class="form-group">
							<label class="col-sm-4 control-label">@Html.LabelFor(x => x.FORM.IdClient)</label>
							<div class="col-sm-6">
                                @(Model.user.Client != null ? Model.user.Client.Name : "N/A")
							</div>
						</div>
                    <div class="form-group">
							<label class="col-sm-4 control-label">@Html.LabelFor(x => x.FORM.DbUserName)</label>
							<div class="col-sm-6">
                                @Model.FORM.DbUserName
							</div>
						</div>
						<div class="form-group">
							<label class="col-sm-4 control-label">@Html.LabelFor(x => x.FORM.FirstName)</label>
							<div class="col-sm-6">
                                @Html.TextBoxFor(x => x.FORM.FirstName, new { @class = "form-control input-sm", @placeholder = "First Name" })
							</div>
						</div>
						<div class="form-group">
							<label class="col-sm-4 control-label">@Html.LabelFor(x => x.FORM.LastName)</label>
							<div class="col-sm-6">
                                @Html.TextBoxFor(x => x.FORM.LastName, new { @class = "form-control input-sm", @placeholder = "Last Name" })
							</div>
						</div>
						
                    <div class="form-group">
							<label class="col-sm-4 control-label">@Html.LabelFor(x => x.FORM.Contact)</label>
							<div class="col-sm-6">
                                @Html.TextBoxFor(x => x.FORM.Contact, new { @class = "form-control input-sm", @placeholder = "Ej: 22225555 (Opcional)" })
							</div>
						</div>
                    <div class="form-group">
							<label class="col-sm-4 control-label">@Html.LabelFor(x => x.FORM.Email)</label>
							<div class="col-sm-6">
                                @Html.TextBoxFor(x => x.FORM.Email, new { @class = "form-control input-sm", @placeholder = "Ej: jsmith@gmail.com" })
							</div>
						</div>									
				</div>
				<div class="row">
					<div class="col-md-6 col-md-offset-4">

                        
                        <input type="submit" class="btn btn-success pull-right" value="Guardar" />
                        
                        @if (User.Identity.Name.ToLower() != Model.FORM.DbUserName.ToLower())
                        {
                        <a href="@Url.Action("Index", "Users")" class="btn btn-primary">Cancel</a>
                        }
                        else {
                            <a href="@Url.Action("Index", "Home")" class="btn btn-primary">Back</a>
                        }
					</div>
				</div>
                </form>
			</section>
@Scripts.Render("~/bundles/custom/manager/users/edit")
<script type="text/javascript">
    $(document).ready(function () {
        init();
    });
</script>

TunnelAppSubscription/Views/Users/EditUser.cshtml
@model TunnelApp.Subscription.Models.Users.UsersViewModel
@using System.Web.Optimization
@{
    ViewBag.Title = "Edit Roles";
}

<div class="row-fluid">
				<ol class="breadcrumb">
					<li><a href="@Url.Action("Index", "Home")">Inicio</a></li>
					<li><a href="@Url.Action("Index", "Manager")">Manager</a></li>
					<li><a href="@Url.Action("Index", "Users")">Users</a></li>
					<li>Edit Roles</li>
				</ol>
			</div>
			<section>
                
				<div class="row-fluid">
					<h3>Edit Roles</h3>
				</div>
                @if (TempData["Mensaje"] != null && !String.IsNullOrEmpty(TempData["Mensaje"].ToString()))
                {
                <div class="alert alert-warning alert-dismissible fadeOutMantenedor" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <strong>@(TempData["Mensaje"])</strong>
                </div>
                }
                <br />
                <form action="@Url.Action("EditUser", "Users")" method="POST" class="form-horizontal">
                    @Html.HiddenFor(x => x.FORM.IdUser)
				<div class="row-fluid">
                    <div class="form-group">
							<label class="col-sm-4 control-label">@Html.LabelFor(x => x.FORM.IdClient)</label>
							<div class="col-sm-6">
                                @(Model.user.Client != null ? Model.user.Client.Name : "N/A")
							</div>
						</div>
						<div class="form-group">
							<label class="col-sm-4 control-label">@Html.LabelFor(x => x.FORM.DbUserName)</label>
							<div class="col-sm-4">
                                <label class="control-label">@Model.FORM.DbUserName</label>
                                 @Html.HiddenFor(m => m.FORM.DbUserName, @Model.FORM.DbUserName)
							</div>
						</div>
                    <div class="form-group">
						    <label class="col-sm-4 control-label">@Html.LabelFor(x => x.FORM.SelectedRoles)</label>
							<div class="col-sm-4">
                                @for (int i = 0; i < Model.FORM.SelectedRoles.Count(); i++)
                                {
                                   <div class="checkbox"><label>@Html.CheckBoxFor(m => m.FORM.SelectedRoles[i].Checked, new { @id = Model.FORM.SelectedRoles[i].IdSelectedRole}) @Model.FORM.SelectedRoles[i].SelectedRole </label></div>
                                   @Html.HiddenFor(m => m.FORM.SelectedRoles[i].IdSelectedRole)
                                   @Html.HiddenFor(m => m.FORM.SelectedRoles[i].SelectedRole)
                                }
							</div>
						</div>
                    					
				</div>
				<div class="row">
					<div class="col-md-4 col-md-offset-4">
						<input type="submit" class="btn btn-success" value="Guardar" />
                        <a href="@Url.Action("Index", "Users")" class="btn btn-primary  pull-right">Cancelar</a>
					</div>
				</div>
                </form>
			</section>
@Scripts.Render("~/bundles/custom/manager/users/userEdit")
<script type="text/javascript">
    $(document).ready(function () {
        init();
    });
</script>

TunnelAppSubscription/Views/Users/Index.cshtml
@model TunnelApp.Subscription.Models.Users.UsersViewModel
@using TunnelApp.Subscription.Models.Accounts
@using System.Web.Optimization
@{
    ViewBag.Title = "Manage Users";
}
<section class="container-fluid">
    <article>
        <div class="row">
		    <ol class="breadcrumb">
			    <li><a href="@Url.Action("Index", "Home")">Home</a></li>
			    <li><a href="@Url.Action("Index", "Manager")">Management</a></li>
				<li><a href="@Url.Action("Index", "Users")">Users</a></li>
			</ol>
		</div>

        <article>
		    <div class="bs-callout bs-callout-JJ">
                <legend>Manage Users</legend>
                <a href="@Url.Action("Create", "Users")" data-toggle="confirmation"  title="Nuevo Usuario" class="btn btn-success">
                    <span class='glyphicon glyphicon-plus-sign'></span> Create New
                </a>

                <button class="btn btn-primary" type="button">
			        Total item <span class="badge">@(Model.Users.Count()-1)</span>
				</button>
		    </div>
		</article>

        <br />
        @if (TempData["Mensaje"] != null && !String.IsNullOrEmpty(TempData["Mensaje"].ToString()))
        {
            <div class="alert alert-success alert-dismissible fadeOutMantenedor" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <strong>@(TempData["Mensaje"])</strong>
            </div>
        }
        <br />
        <div class="row">
            <div class="table-responsive">                            
                <table id="list-manager" class="table table-striped table-condensed display">
                    <thead>
                        <tr>
                            <th>@Html.DisplayName("Client")</th>
                            <th>@Html.DisplayName("User Name")</th>
                            <th>@Html.DisplayName("First Name")</th>
                            <th>@Html.DisplayName("Last Name")</th>
                            <th>@Html.DisplayName("Contact")</th>
                            <th>@Html.DisplayName("Email")</th>
                            <th>@Html.DisplayName("Created At")</th>
                            <th>Edit Private Data</th>
                            <th>Edit Roles</th>
                            <th>Delete</th>
                            <th>Reset Password   <i class="glyphicon glyphicon-question-sign" data-toggle='tooltip' data-placement='bottom' title="Para mayor información, hazme click"></i></th>
                            
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.Users)
                        {
                            if (item.UserName.ToLower().Equals(User.Identity.Name.ToLower())) { continue; }
                            <tr>
                                <td>@(item.Client != null ? item.Client.Name : "N/A")</td>
                                <td>@Html.DisplayFor(modelItem => item.UserName)</td>
                                <td>@Html.DisplayFor(modelItem => item.FirstName)</td>
                                <td>@Html.DisplayFor(modelItem => item.LastName)</td>
                                <td>@Html.DisplayFor(modelItem => item.Contact)</td>
                                <td>@Html.DisplayFor(modelItem => item.Email)</td>
                                <td>@Html.DisplayFor(modelItem => item.CreatedAt)</td>
                                <td><a href="@Url.Action("Edit", "Users", new { IdUser = item.IdUser })" class="btn btn-default"><span class='glyphicon glyphicon-edit'></span></a></td>
                                <td><a href="@Url.Action("EditUser", "Users", new { IdUser = item.IdUser })" class="btn btn-default"><span class='fa fa-user'></span></a></td>
                                <td>
                                    @*@if (!Model.tieneMantenciones(item))
                                    {
                                    *@<a href="@Url.Action("Delete", "Users", new { IdUser = item.IdUser })" class="btn btn-default" onclick="if(!confirm('Está a punto de eliminar a este usuario.\n¿Desea continuar?.')) return false;"><span class='glyphicon glyphicon-trash'></span></a>
                                    @*}*@
                                </td>
                                <td><a href="@Url.Action("ResetPassword", "Users", new { IdUser = item.IdUser })" class="btn btn-default" onclick="if(!confirm('Está a punto de resetear la contraseña a este usuario.\n¿Desea continuar?.')) return false;"><span class='glyphicon glyphicon-repeat'></span></a> </td>
                                
                            </tr>
                        }
                    </tbody>
                </table>
			</div>
		</div>
    </article>
</section>

<div class="modal fade" id="ModalInfoResetPassword" tabindex="-1" role="dialog" aria-labelledby="">
    <div class="modal-dialog" role="document">
	    <div class="modal-content">
		    <div class="modal-header">
			    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
				    <span aria-hidden="true">&times;</span>
				</button>
			    <h4 class="modal-title" id="myModalLabel">Resetear Contraseña</h4>
			</div>
			<div id="contenido-modal" class="modal-body">
                <p class="text-info">
                    Al hacer click a uno de estos botones, la contraseña del usuario volverá a un valor por defecto.
                </p>
                <p class="text-info">
                    Una vez realizada la acción de Reseteo, debe notificar al usuario el cambio de contraseña, indicándole que debe ingresar nuevamente al sistema.
                </p>
                <p class="text-info">
                    El valor por defecto es : (nombre de usuario)@@skava
                </p>
                
			</div>
			<div class="modal-footer">
			    <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
			</div>
		</div>
	</div>
</div>

@Scripts.Render("~/bundles/custom/manager/users/list")
<script type="text/javascript">
    $(document).ready(function () {
        init();
    });
</script>