TunnelApp/Controllers/ParametersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TunnelApp.Controllers
{
    public class ParametersController : Controller
    {
        //
        // GET: /Parameters/

        public ActionResult Index()
        {
            return View();
        }

        //
        // GET: /Parameters/Projects

        public ActionResult Projects()
        {
            return RedirectToAction("Index", "Projects");
        }

        //
        // GET: /Parameters/Tunnels

        public ActionResult Tunnels()
        {
            return RedirectToAction("Index", "Tunnels");
        }

        //
        // GET: /Parameters/Faces

        public ActionResult Faces()
        {
            return RedirectToAction("Index", "Faces");
        }

        //
        // GET: /Parameters/SupportRecommendations

        public ActionResult SupportRecommendations()
        {
            return RedirectToAction("Index", "SupportRecommendations");
        }

        //
        // GET: /Parameters/Users

        public ActionResult Users()
        {
            return RedirectToAction("Index", "Users");
        }

    }
}

TunnelApp/Controllers/ReportingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TunnelApp.Controllers
{
    public class ReportingController : Controller
    {
        //
        // GET: /Reporting/

        public ActionResult Index()
        {
            return View();
        }

    }
}

TunnelApp/Views/Shared/_Layout.cshtml
@using System.Web.Optimization
@using TunnelApp.Models.Accounts
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - TunnelAPP Admin Site by Skava</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />

        @Styles.Render("~/Content/css")
        @Styles.Render("~/Content/bootstrap/css")

        @Styles.Render("~/Content/external/css")

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/jqueryui")
       
        @Scripts.Render("~/bundles/bootstrap")
       
        @Scripts.Render("~/bundles/external")

        @Scripts.Render("~/bundles/custom")

        @RenderSection("scripts", required: false)
    </head>
    <body>
        
        @*<header id="client-app-header" class="navbar-static-top">
            <div class="col-md-12">
				<div class="navbar-header">
                    @if (Request.IsAuthenticated) {
					<button type="button" id="toggleMenu" class="toggle_menu" aria-label="Justify">
						<span class="glyphicon glyphicon-menu-hamburger" aria-hidden="true"></span>
					</button>
                    }
					<div class="Logo">
						<a href="@Url.Action("Index", "Home")" title="Home">
							<img class="ImgLogo" src="@Url.Content("~/Images/SmallLogo.png")" />
						</a>					
						<span class="logo_desc">TunnelAPP Admin Site <small style="vertical-align: bottom;">by Skava</small></span>
					</div>

				</div>*@
                @Html.Partial("_LoginPartial")

			@*</div>
        </header>*@

        @Html.Partial("_LoginPartialMenu")

        <div class="wrapper wrapper__minify">
			<section>
            @RenderSection("featured",false)
            @RenderBody()
			</section>

		</div>
    </body>
</html>

TunnelApp/Views/Shared/_LoginPartialMenu.cshtml
@if (Request.IsAuthenticated)
{
<nav class="vertical_nav no-seleccionable vertical_nav__minify">
			<ul id="js-menu" class="menu">

				<li class="menu--item">
					<a href="@Url.Action("Index", "Home")" class="menu--link" title="Inicio">
						<span class="menu--icon glyphicon glyphicon-home" aria-hidden="true"></span>
						<span class="menu--label"> Inicio</span>
					</a>
				</li>

                @if (HttpContext.Current.User.IsInRole("analyst"))
                {
                     <li class="menu--item">
                    <a href="@Url.Action("Index", "Reporting")" class="menu--link" title="Reportes">
						<span class="menu--icon  glyphicon glyphicon-duplicate"></span>
						<span class="menu--label">Reportes</span>
					</a>
				</li>

				
                }
                
                @if (HttpContext.Current.User.IsInRole("geologist"))
                {
                     <li class="menu--item">
                    <a href="@Url.Action("Index", "Mapping")" class="menu--link" title="Mapping Templates">
						<span class="menu--icon fa fa-th-list"></span>
						<span class="menu--label">Mapping Templates</span>
					</a>
				</li>

				
                }

                

                @if (HttpContext.Current.User.IsInRole("administrator"))
                {
                    <li class="menu--item">
					<a href="@Url.Action("Index", "Parameters")" class="menu--link" title="Settings">
						<span class="menu--icon  glyphicon glyphicon-cog"></span>
						<span class="menu--label">Settings</span>
					</a>

                   
				</li>
                }

			</ul>

			<button id="collapse_menu" class="collapse_menu">
				<i class="collapse_menu--icon  fa fa-fw"></i>
				<span class="collapse_menu--label">Colapsar Menu</span>
			</button>
</nav>
}